/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as WorkspacesRouteImport } from './routes/workspaces'
import { Route as InvitesTokenRouteImport } from './routes/invites.$token'
import { Route as WorkspacesIndexRouteImport } from './routes/workspaces.index'
import { Route as WorkspacesCodeRouteImport } from './routes/workspaces.$code'
import { Route as WorkspacesCreateWorkspaceRouteImport } from './routes/workspaces.create-workspace'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as WorkspacesCodeIndexRouteImport } from './routes/workspaces.$code.index'
import { Route as WorkspacesCodeDocumentsRouteImport } from './routes/workspaces.$code.documents'
import { Route as WorkspacesCodeIssuesRouteImport } from './routes/workspaces.$code.issues'
import { Route as WorkspacesCodeSettingsRouteImport } from './routes/workspaces.$code.settings'
import { Route as WorkspacesCodeDocumentsIndexRouteImport } from './routes/workspaces.$code.documents.index'
import { Route as WorkspacesCodeDocumentsDocumentIdRouteImport } from './routes/workspaces.$code.documents.$documentId'
import { Route as WorkspacesCodeIssuesIndexRouteImport } from './routes/workspaces.$code.issues.index'
import { Route as WorkspacesCodeIssuesIssueNumberRouteImport } from './routes/workspaces.$code.issues.$issueNumber'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitesTokenRoute = InvitesTokenRouteImport.update({
  id: '/invites/$token',
  path: '/invites/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesIndexRoute = WorkspacesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspacesRoute,
} as any)
const WorkspacesCodeRoute = WorkspacesCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => WorkspacesRoute,
} as any)
const WorkspacesCreateWorkspaceRoute =
  WorkspacesCreateWorkspaceRouteImport.update({
    id: '/create-workspace',
    path: '/create-workspace',
    getParentRoute: () => WorkspacesRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesCodeIndexRoute = WorkspacesCodeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspacesCodeRoute,
} as any)
const WorkspacesCodeDocumentsRoute = WorkspacesCodeDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => WorkspacesCodeRoute,
} as any)
const WorkspacesCodeIssuesRoute = WorkspacesCodeIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => WorkspacesCodeRoute,
} as any)
const WorkspacesCodeSettingsRoute = WorkspacesCodeSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkspacesCodeRoute,
} as any)
const WorkspacesCodeDocumentsIndexRoute =
  WorkspacesCodeDocumentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspacesCodeDocumentsRoute,
  } as any)
const WorkspacesCodeDocumentsDocumentIdRoute =
  WorkspacesCodeDocumentsDocumentIdRouteImport.update({
    id: '/$documentId',
    path: '/$documentId',
    getParentRoute: () => WorkspacesCodeDocumentsRoute,
  } as any)
const WorkspacesCodeIssuesIndexRoute =
  WorkspacesCodeIssuesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspacesCodeIssuesRoute,
  } as any)
const WorkspacesCodeIssuesIssueNumberRoute =
  WorkspacesCodeIssuesIssueNumberRouteImport.update({
    id: '/$issueNumber',
    path: '/$issueNumber',
    getParentRoute: () => WorkspacesCodeIssuesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/workspaces': typeof WorkspacesRouteWithChildren
  '/invites/$token': typeof InvitesTokenRoute
  '/workspaces/$code': typeof WorkspacesCodeRouteWithChildren
  '/workspaces/create-workspace': typeof WorkspacesCreateWorkspaceRoute
  '/workspaces/': typeof WorkspacesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/workspaces/$code/documents': typeof WorkspacesCodeDocumentsRouteWithChildren
  '/workspaces/$code/issues': typeof WorkspacesCodeIssuesRouteWithChildren
  '/workspaces/$code/settings': typeof WorkspacesCodeSettingsRoute
  '/workspaces/$code/': typeof WorkspacesCodeIndexRoute
  '/workspaces/$code/documents/$documentId': typeof WorkspacesCodeDocumentsDocumentIdRoute
  '/workspaces/$code/issues/$issueNumber': typeof WorkspacesCodeIssuesIssueNumberRoute
  '/workspaces/$code/documents/': typeof WorkspacesCodeDocumentsIndexRoute
  '/workspaces/$code/issues/': typeof WorkspacesCodeIssuesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/invites/$token': typeof InvitesTokenRoute
  '/workspaces/create-workspace': typeof WorkspacesCreateWorkspaceRoute
  '/workspaces': typeof WorkspacesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/workspaces/$code/settings': typeof WorkspacesCodeSettingsRoute
  '/workspaces/$code': typeof WorkspacesCodeIndexRoute
  '/workspaces/$code/documents/$documentId': typeof WorkspacesCodeDocumentsDocumentIdRoute
  '/workspaces/$code/issues/$issueNumber': typeof WorkspacesCodeIssuesIssueNumberRoute
  '/workspaces/$code/documents': typeof WorkspacesCodeDocumentsIndexRoute
  '/workspaces/$code/issues': typeof WorkspacesCodeIssuesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/workspaces': typeof WorkspacesRouteWithChildren
  '/invites/$token': typeof InvitesTokenRoute
  '/workspaces/$code': typeof WorkspacesCodeRouteWithChildren
  '/workspaces/create-workspace': typeof WorkspacesCreateWorkspaceRoute
  '/workspaces/': typeof WorkspacesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/workspaces/$code/documents': typeof WorkspacesCodeDocumentsRouteWithChildren
  '/workspaces/$code/issues': typeof WorkspacesCodeIssuesRouteWithChildren
  '/workspaces/$code/settings': typeof WorkspacesCodeSettingsRoute
  '/workspaces/$code/': typeof WorkspacesCodeIndexRoute
  '/workspaces/$code/documents/$documentId': typeof WorkspacesCodeDocumentsDocumentIdRoute
  '/workspaces/$code/issues/$issueNumber': typeof WorkspacesCodeIssuesIssueNumberRoute
  '/workspaces/$code/documents/': typeof WorkspacesCodeDocumentsIndexRoute
  '/workspaces/$code/issues/': typeof WorkspacesCodeIssuesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/workspaces'
    | '/invites/$token'
    | '/workspaces/$code'
    | '/workspaces/create-workspace'
    | '/workspaces/'
    | '/api/auth/$'
    | '/workspaces/$code/documents'
    | '/workspaces/$code/issues'
    | '/workspaces/$code/settings'
    | '/workspaces/$code/'
    | '/workspaces/$code/documents/$documentId'
    | '/workspaces/$code/issues/$issueNumber'
    | '/workspaces/$code/documents/'
    | '/workspaces/$code/issues/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/invites/$token'
    | '/workspaces/create-workspace'
    | '/workspaces'
    | '/api/auth/$'
    | '/workspaces/$code/settings'
    | '/workspaces/$code'
    | '/workspaces/$code/documents/$documentId'
    | '/workspaces/$code/issues/$issueNumber'
    | '/workspaces/$code/documents'
    | '/workspaces/$code/issues'
  id:
    | '__root__'
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/workspaces'
    | '/invites/$token'
    | '/workspaces/$code'
    | '/workspaces/create-workspace'
    | '/workspaces/'
    | '/api/auth/$'
    | '/workspaces/$code/documents'
    | '/workspaces/$code/issues'
    | '/workspaces/$code/settings'
    | '/workspaces/$code/'
    | '/workspaces/$code/documents/$documentId'
    | '/workspaces/$code/issues/$issueNumber'
    | '/workspaces/$code/documents/'
    | '/workspaces/$code/issues/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  WorkspacesRoute: typeof WorkspacesRouteWithChildren
  InvitesTokenRoute: typeof InvitesTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invites/$token': {
      id: '/invites/$token'
      path: '/invites/$token'
      fullPath: '/invites/$token'
      preLoaderRoute: typeof InvitesTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/': {
      id: '/workspaces/'
      path: '/'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof WorkspacesIndexRouteImport
      parentRoute: typeof WorkspacesRoute
    }
    '/workspaces/$code': {
      id: '/workspaces/$code'
      path: '/$code'
      fullPath: '/workspaces/$code'
      preLoaderRoute: typeof WorkspacesCodeRouteImport
      parentRoute: typeof WorkspacesRoute
    }
    '/workspaces/create-workspace': {
      id: '/workspaces/create-workspace'
      path: '/create-workspace'
      fullPath: '/workspaces/create-workspace'
      preLoaderRoute: typeof WorkspacesCreateWorkspaceRouteImport
      parentRoute: typeof WorkspacesRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/$code/': {
      id: '/workspaces/$code/'
      path: '/'
      fullPath: '/workspaces/$code/'
      preLoaderRoute: typeof WorkspacesCodeIndexRouteImport
      parentRoute: typeof WorkspacesCodeRoute
    }
    '/workspaces/$code/documents': {
      id: '/workspaces/$code/documents'
      path: '/documents'
      fullPath: '/workspaces/$code/documents'
      preLoaderRoute: typeof WorkspacesCodeDocumentsRouteImport
      parentRoute: typeof WorkspacesCodeRoute
    }
    '/workspaces/$code/issues': {
      id: '/workspaces/$code/issues'
      path: '/issues'
      fullPath: '/workspaces/$code/issues'
      preLoaderRoute: typeof WorkspacesCodeIssuesRouteImport
      parentRoute: typeof WorkspacesCodeRoute
    }
    '/workspaces/$code/settings': {
      id: '/workspaces/$code/settings'
      path: '/settings'
      fullPath: '/workspaces/$code/settings'
      preLoaderRoute: typeof WorkspacesCodeSettingsRouteImport
      parentRoute: typeof WorkspacesCodeRoute
    }
    '/workspaces/$code/documents/': {
      id: '/workspaces/$code/documents/'
      path: '/'
      fullPath: '/workspaces/$code/documents/'
      preLoaderRoute: typeof WorkspacesCodeDocumentsIndexRouteImport
      parentRoute: typeof WorkspacesCodeDocumentsRoute
    }
    '/workspaces/$code/documents/$documentId': {
      id: '/workspaces/$code/documents/$documentId'
      path: '/$documentId'
      fullPath: '/workspaces/$code/documents/$documentId'
      preLoaderRoute: typeof WorkspacesCodeDocumentsDocumentIdRouteImport
      parentRoute: typeof WorkspacesCodeDocumentsRoute
    }
    '/workspaces/$code/issues/': {
      id: '/workspaces/$code/issues/'
      path: '/'
      fullPath: '/workspaces/$code/issues/'
      preLoaderRoute: typeof WorkspacesCodeIssuesIndexRouteImport
      parentRoute: typeof WorkspacesCodeIssuesRoute
    }
    '/workspaces/$code/issues/$issueNumber': {
      id: '/workspaces/$code/issues/$issueNumber'
      path: '/$issueNumber'
      fullPath: '/workspaces/$code/issues/$issueNumber'
      preLoaderRoute: typeof WorkspacesCodeIssuesIssueNumberRouteImport
      parentRoute: typeof WorkspacesCodeIssuesRoute
    }
  }
}

interface WorkspacesCodeDocumentsRouteChildren {
  WorkspacesCodeDocumentsDocumentIdRoute: typeof WorkspacesCodeDocumentsDocumentIdRoute
  WorkspacesCodeDocumentsIndexRoute: typeof WorkspacesCodeDocumentsIndexRoute
}

const WorkspacesCodeDocumentsRouteChildren: WorkspacesCodeDocumentsRouteChildren =
  {
    WorkspacesCodeDocumentsDocumentIdRoute:
      WorkspacesCodeDocumentsDocumentIdRoute,
    WorkspacesCodeDocumentsIndexRoute: WorkspacesCodeDocumentsIndexRoute,
  }

const WorkspacesCodeDocumentsRouteWithChildren =
  WorkspacesCodeDocumentsRoute._addFileChildren(
    WorkspacesCodeDocumentsRouteChildren,
  )

interface WorkspacesCodeIssuesRouteChildren {
  WorkspacesCodeIssuesIssueNumberRoute: typeof WorkspacesCodeIssuesIssueNumberRoute
  WorkspacesCodeIssuesIndexRoute: typeof WorkspacesCodeIssuesIndexRoute
}

const WorkspacesCodeIssuesRouteChildren: WorkspacesCodeIssuesRouteChildren = {
  WorkspacesCodeIssuesIssueNumberRoute: WorkspacesCodeIssuesIssueNumberRoute,
  WorkspacesCodeIssuesIndexRoute: WorkspacesCodeIssuesIndexRoute,
}

const WorkspacesCodeIssuesRouteWithChildren =
  WorkspacesCodeIssuesRoute._addFileChildren(WorkspacesCodeIssuesRouteChildren)

interface WorkspacesCodeRouteChildren {
  WorkspacesCodeDocumentsRoute: typeof WorkspacesCodeDocumentsRouteWithChildren
  WorkspacesCodeIssuesRoute: typeof WorkspacesCodeIssuesRouteWithChildren
  WorkspacesCodeSettingsRoute: typeof WorkspacesCodeSettingsRoute
  WorkspacesCodeIndexRoute: typeof WorkspacesCodeIndexRoute
}

const WorkspacesCodeRouteChildren: WorkspacesCodeRouteChildren = {
  WorkspacesCodeDocumentsRoute: WorkspacesCodeDocumentsRouteWithChildren,
  WorkspacesCodeIssuesRoute: WorkspacesCodeIssuesRouteWithChildren,
  WorkspacesCodeSettingsRoute: WorkspacesCodeSettingsRoute,
  WorkspacesCodeIndexRoute: WorkspacesCodeIndexRoute,
}

const WorkspacesCodeRouteWithChildren = WorkspacesCodeRoute._addFileChildren(
  WorkspacesCodeRouteChildren,
)

interface WorkspacesRouteChildren {
  WorkspacesCodeRoute: typeof WorkspacesCodeRouteWithChildren
  WorkspacesCreateWorkspaceRoute: typeof WorkspacesCreateWorkspaceRoute
  WorkspacesIndexRoute: typeof WorkspacesIndexRoute
}

const WorkspacesRouteChildren: WorkspacesRouteChildren = {
  WorkspacesCodeRoute: WorkspacesCodeRouteWithChildren,
  WorkspacesCreateWorkspaceRoute: WorkspacesCreateWorkspaceRoute,
  WorkspacesIndexRoute: WorkspacesIndexRoute,
}

const WorkspacesRouteWithChildren = WorkspacesRoute._addFileChildren(
  WorkspacesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  WorkspacesRoute: WorkspacesRouteWithChildren,
  InvitesTokenRoute: InvitesTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
