/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as WorkspacesRouteImport } from './routes/workspaces'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppCodeRouteImport } from './routes/app.$code'
import { Route as AppAccountRouteImport } from './routes/app.account'
import { Route as AppCreateWorkspaceRouteImport } from './routes/app.create-workspace'
import { Route as FilesFileIdRouteImport } from './routes/files.$fileId'
import { Route as InvitesTokenRouteImport } from './routes/invites.$token'
import { Route as WorkspacesSplatRouteImport } from './routes/workspaces.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppCodeIndexRouteImport } from './routes/app.$code.index'
import { Route as AppCodeDocumentsRouteImport } from './routes/app.$code.documents'
import { Route as AppCodeIssuesRouteImport } from './routes/app.$code.issues'
import { Route as AppCodeSettingsRouteImport } from './routes/app.$code.settings'
import { Route as AppCodeDocumentsIndexRouteImport } from './routes/app.$code.documents.index'
import { Route as AppCodeDocumentsDocumentIdRouteImport } from './routes/app.$code.documents.$documentId'
import { Route as AppCodeIssuesIndexRouteImport } from './routes/app.$code.issues.index'
import { Route as AppCodeIssuesIssueNumberRouteImport } from './routes/app.$code.issues.$issueNumber'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCodeRoute = AppCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateWorkspaceRoute = AppCreateWorkspaceRouteImport.update({
  id: '/create-workspace',
  path: '/create-workspace',
  getParentRoute: () => AppRoute,
} as any)
const FilesFileIdRoute = FilesFileIdRouteImport.update({
  id: '/files/$fileId',
  path: '/files/$fileId',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitesTokenRoute = InvitesTokenRouteImport.update({
  id: '/invites/$token',
  path: '/invites/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesSplatRoute = WorkspacesSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => WorkspacesRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCodeIndexRoute = AppCodeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCodeRoute,
} as any)
const AppCodeDocumentsRoute = AppCodeDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppCodeRoute,
} as any)
const AppCodeIssuesRoute = AppCodeIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => AppCodeRoute,
} as any)
const AppCodeSettingsRoute = AppCodeSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppCodeRoute,
} as any)
const AppCodeDocumentsIndexRoute = AppCodeDocumentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCodeDocumentsRoute,
} as any)
const AppCodeDocumentsDocumentIdRoute =
  AppCodeDocumentsDocumentIdRouteImport.update({
    id: '/$documentId',
    path: '/$documentId',
    getParentRoute: () => AppCodeDocumentsRoute,
  } as any)
const AppCodeIssuesIndexRoute = AppCodeIssuesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCodeIssuesRoute,
} as any)
const AppCodeIssuesIssueNumberRoute =
  AppCodeIssuesIssueNumberRouteImport.update({
    id: '/$issueNumber',
    path: '/$issueNumber',
    getParentRoute: () => AppCodeIssuesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/workspaces': typeof WorkspacesRouteWithChildren
  '/api/mcp': typeof ApiMcpRoute
  '/app/$code': typeof AppCodeRouteWithChildren
  '/app/account': typeof AppAccountRoute
  '/app/create-workspace': typeof AppCreateWorkspaceRoute
  '/files/$fileId': typeof FilesFileIdRoute
  '/invites/$token': typeof InvitesTokenRoute
  '/workspaces/$': typeof WorkspacesSplatRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/$code/documents': typeof AppCodeDocumentsRouteWithChildren
  '/app/$code/issues': typeof AppCodeIssuesRouteWithChildren
  '/app/$code/settings': typeof AppCodeSettingsRoute
  '/app/$code/': typeof AppCodeIndexRoute
  '/app/$code/documents/$documentId': typeof AppCodeDocumentsDocumentIdRoute
  '/app/$code/issues/$issueNumber': typeof AppCodeIssuesIssueNumberRoute
  '/app/$code/documents/': typeof AppCodeDocumentsIndexRoute
  '/app/$code/issues/': typeof AppCodeIssuesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/workspaces': typeof WorkspacesRouteWithChildren
  '/api/mcp': typeof ApiMcpRoute
  '/app/account': typeof AppAccountRoute
  '/app/create-workspace': typeof AppCreateWorkspaceRoute
  '/files/$fileId': typeof FilesFileIdRoute
  '/invites/$token': typeof InvitesTokenRoute
  '/workspaces/$': typeof WorkspacesSplatRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/$code/settings': typeof AppCodeSettingsRoute
  '/app/$code': typeof AppCodeIndexRoute
  '/app/$code/documents/$documentId': typeof AppCodeDocumentsDocumentIdRoute
  '/app/$code/issues/$issueNumber': typeof AppCodeIssuesIssueNumberRoute
  '/app/$code/documents': typeof AppCodeDocumentsIndexRoute
  '/app/$code/issues': typeof AppCodeIssuesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/workspaces': typeof WorkspacesRouteWithChildren
  '/api/mcp': typeof ApiMcpRoute
  '/app/$code': typeof AppCodeRouteWithChildren
  '/app/account': typeof AppAccountRoute
  '/app/create-workspace': typeof AppCreateWorkspaceRoute
  '/files/$fileId': typeof FilesFileIdRoute
  '/invites/$token': typeof InvitesTokenRoute
  '/workspaces/$': typeof WorkspacesSplatRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/$code/documents': typeof AppCodeDocumentsRouteWithChildren
  '/app/$code/issues': typeof AppCodeIssuesRouteWithChildren
  '/app/$code/settings': typeof AppCodeSettingsRoute
  '/app/$code/': typeof AppCodeIndexRoute
  '/app/$code/documents/$documentId': typeof AppCodeDocumentsDocumentIdRoute
  '/app/$code/issues/$issueNumber': typeof AppCodeIssuesIssueNumberRoute
  '/app/$code/documents/': typeof AppCodeDocumentsIndexRoute
  '/app/$code/issues/': typeof AppCodeIssuesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/sign-in'
    | '/sign-up'
    | '/workspaces'
    | '/api/mcp'
    | '/app/$code'
    | '/app/account'
    | '/app/create-workspace'
    | '/files/$fileId'
    | '/invites/$token'
    | '/workspaces/$'
    | '/app/'
    | '/api/auth/$'
    | '/app/$code/documents'
    | '/app/$code/issues'
    | '/app/$code/settings'
    | '/app/$code/'
    | '/app/$code/documents/$documentId'
    | '/app/$code/issues/$issueNumber'
    | '/app/$code/documents/'
    | '/app/$code/issues/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/workspaces'
    | '/api/mcp'
    | '/app/account'
    | '/app/create-workspace'
    | '/files/$fileId'
    | '/invites/$token'
    | '/workspaces/$'
    | '/app'
    | '/api/auth/$'
    | '/app/$code/settings'
    | '/app/$code'
    | '/app/$code/documents/$documentId'
    | '/app/$code/issues/$issueNumber'
    | '/app/$code/documents'
    | '/app/$code/issues'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/sign-in'
    | '/sign-up'
    | '/workspaces'
    | '/api/mcp'
    | '/app/$code'
    | '/app/account'
    | '/app/create-workspace'
    | '/files/$fileId'
    | '/invites/$token'
    | '/workspaces/$'
    | '/app/'
    | '/api/auth/$'
    | '/app/$code/documents'
    | '/app/$code/issues'
    | '/app/$code/settings'
    | '/app/$code/'
    | '/app/$code/documents/$documentId'
    | '/app/$code/issues/$issueNumber'
    | '/app/$code/documents/'
    | '/app/$code/issues/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  WorkspacesRoute: typeof WorkspacesRouteWithChildren
  ApiMcpRoute: typeof ApiMcpRoute
  FilesFileIdRoute: typeof FilesFileIdRoute
  InvitesTokenRoute: typeof InvitesTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$code': {
      id: '/app/$code'
      path: '/$code'
      fullPath: '/app/$code'
      preLoaderRoute: typeof AppCodeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/account': {
      id: '/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/create-workspace': {
      id: '/app/create-workspace'
      path: '/create-workspace'
      fullPath: '/app/create-workspace'
      preLoaderRoute: typeof AppCreateWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/files/$fileId': {
      id: '/files/$fileId'
      path: '/files/$fileId'
      fullPath: '/files/$fileId'
      preLoaderRoute: typeof FilesFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invites/$token': {
      id: '/invites/$token'
      path: '/invites/$token'
      fullPath: '/invites/$token'
      preLoaderRoute: typeof InvitesTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/$': {
      id: '/workspaces/$'
      path: '/$'
      fullPath: '/workspaces/$'
      preLoaderRoute: typeof WorkspacesSplatRouteImport
      parentRoute: typeof WorkspacesRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$code/': {
      id: '/app/$code/'
      path: '/'
      fullPath: '/app/$code/'
      preLoaderRoute: typeof AppCodeIndexRouteImport
      parentRoute: typeof AppCodeRoute
    }
    '/app/$code/documents': {
      id: '/app/$code/documents'
      path: '/documents'
      fullPath: '/app/$code/documents'
      preLoaderRoute: typeof AppCodeDocumentsRouteImport
      parentRoute: typeof AppCodeRoute
    }
    '/app/$code/issues': {
      id: '/app/$code/issues'
      path: '/issues'
      fullPath: '/app/$code/issues'
      preLoaderRoute: typeof AppCodeIssuesRouteImport
      parentRoute: typeof AppCodeRoute
    }
    '/app/$code/settings': {
      id: '/app/$code/settings'
      path: '/settings'
      fullPath: '/app/$code/settings'
      preLoaderRoute: typeof AppCodeSettingsRouteImport
      parentRoute: typeof AppCodeRoute
    }
    '/app/$code/documents/': {
      id: '/app/$code/documents/'
      path: '/'
      fullPath: '/app/$code/documents/'
      preLoaderRoute: typeof AppCodeDocumentsIndexRouteImport
      parentRoute: typeof AppCodeDocumentsRoute
    }
    '/app/$code/documents/$documentId': {
      id: '/app/$code/documents/$documentId'
      path: '/$documentId'
      fullPath: '/app/$code/documents/$documentId'
      preLoaderRoute: typeof AppCodeDocumentsDocumentIdRouteImport
      parentRoute: typeof AppCodeDocumentsRoute
    }
    '/app/$code/issues/': {
      id: '/app/$code/issues/'
      path: '/'
      fullPath: '/app/$code/issues/'
      preLoaderRoute: typeof AppCodeIssuesIndexRouteImport
      parentRoute: typeof AppCodeIssuesRoute
    }
    '/app/$code/issues/$issueNumber': {
      id: '/app/$code/issues/$issueNumber'
      path: '/$issueNumber'
      fullPath: '/app/$code/issues/$issueNumber'
      preLoaderRoute: typeof AppCodeIssuesIssueNumberRouteImport
      parentRoute: typeof AppCodeIssuesRoute
    }
  }
}

interface AppCodeDocumentsRouteChildren {
  AppCodeDocumentsDocumentIdRoute: typeof AppCodeDocumentsDocumentIdRoute
  AppCodeDocumentsIndexRoute: typeof AppCodeDocumentsIndexRoute
}

const AppCodeDocumentsRouteChildren: AppCodeDocumentsRouteChildren = {
  AppCodeDocumentsDocumentIdRoute: AppCodeDocumentsDocumentIdRoute,
  AppCodeDocumentsIndexRoute: AppCodeDocumentsIndexRoute,
}

const AppCodeDocumentsRouteWithChildren =
  AppCodeDocumentsRoute._addFileChildren(AppCodeDocumentsRouteChildren)

interface AppCodeIssuesRouteChildren {
  AppCodeIssuesIssueNumberRoute: typeof AppCodeIssuesIssueNumberRoute
  AppCodeIssuesIndexRoute: typeof AppCodeIssuesIndexRoute
}

const AppCodeIssuesRouteChildren: AppCodeIssuesRouteChildren = {
  AppCodeIssuesIssueNumberRoute: AppCodeIssuesIssueNumberRoute,
  AppCodeIssuesIndexRoute: AppCodeIssuesIndexRoute,
}

const AppCodeIssuesRouteWithChildren = AppCodeIssuesRoute._addFileChildren(
  AppCodeIssuesRouteChildren,
)

interface AppCodeRouteChildren {
  AppCodeDocumentsRoute: typeof AppCodeDocumentsRouteWithChildren
  AppCodeIssuesRoute: typeof AppCodeIssuesRouteWithChildren
  AppCodeSettingsRoute: typeof AppCodeSettingsRoute
  AppCodeIndexRoute: typeof AppCodeIndexRoute
}

const AppCodeRouteChildren: AppCodeRouteChildren = {
  AppCodeDocumentsRoute: AppCodeDocumentsRouteWithChildren,
  AppCodeIssuesRoute: AppCodeIssuesRouteWithChildren,
  AppCodeSettingsRoute: AppCodeSettingsRoute,
  AppCodeIndexRoute: AppCodeIndexRoute,
}

const AppCodeRouteWithChildren =
  AppCodeRoute._addFileChildren(AppCodeRouteChildren)

interface AppRouteChildren {
  AppCodeRoute: typeof AppCodeRouteWithChildren
  AppAccountRoute: typeof AppAccountRoute
  AppCreateWorkspaceRoute: typeof AppCreateWorkspaceRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCodeRoute: AppCodeRouteWithChildren,
  AppAccountRoute: AppAccountRoute,
  AppCreateWorkspaceRoute: AppCreateWorkspaceRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface WorkspacesRouteChildren {
  WorkspacesSplatRoute: typeof WorkspacesSplatRoute
}

const WorkspacesRouteChildren: WorkspacesRouteChildren = {
  WorkspacesSplatRoute: WorkspacesSplatRoute,
}

const WorkspacesRouteWithChildren = WorkspacesRoute._addFileChildren(
  WorkspacesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  WorkspacesRoute: WorkspacesRouteWithChildren,
  ApiMcpRoute: ApiMcpRoute,
  FilesFileIdRoute: FilesFileIdRoute,
  InvitesTokenRoute: InvitesTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
